### ISSUE TITLE
Add printer-friendly style

### ISSUE THREAD

**Issue by martijnvankekem** [sparksuite/simple-html-invoice-template#24]
Add a custom style that is more friendly to printers.

**Comment by martijnvankekem** [comment]
Suggested, tested code:

```
@media print {
  .invoice-box {
    max-width: unset;
    box-shadow: none;
    border: 0px;
  }
}
```

**Comment by WesCossick** [comment]
Is there a specific issue with the appearance of the invoice when printing? Printing the [demo page](https://sparksuite.github.io/simple-html-invoice-template/) from Chrome on macOS looks fine:

<img width="1185" alt="Screen Shot 2021-12-30 at 4 01 25 PM" src="https://user-images.githubusercontent.com/3850064/147790728-8a741c44-b15e-478a-905f-9b4ae670eb90.png">

**Comment by martijnvankekem** [comment]
It does look fine, but with the top text removed in a production environment, the border + box shadow only doesn't really looks invoice like in my opinion. It's fine for web view, but the code above gives it a more natural invoice layout when printed.

This is a preference thing ofcourse, but it was just a suggestion.

**Comment by WesCossick** [comment]
Okay, I see what you mean. How the invoice should be styled when printing depends pretty heavily on where/how the invoice is displayed. If the invoice is the primary or only element on the page, then the `@print` styling you proposed definitely makes sense. But, if there are other elements on the page, it might make more sense to leave some form of a border and/or box-shadow to delineate between the invoice and other elements on the page.

For the sake of simplicity, I think it's best to not include any default `@print` styling in the HTML file. That way, the invoice appears the same when printing as it does when viewing it on a screen. Then, it'd be up to the engineers using this invoice template to apply the appropriate `@print` styles based on their unique context.

However, it might be worth adding a "Print styling" section above the "RTL" section in the README. It could include your suggested code above, and would help prevent engineers from accidentally overlooking print styling. Would you be interested in submitting a PR for that?

**Comment by martijnvankekem** [comment]
Definitely agree! PR just created.
