### ISSUE TITLE
What if content is longer than 1 page

### ISSUE THREAD

**Issue by bouchtaoui-dev** [sparksuite/simple-html-invoice-template#27]
First, thank you for sharing this nice template. I just want to ask, do we have a solution in case the content is longer than 1 page? Because printing a html page longer than 1 page, can be ugly because it may cut a line of text and continues in a new page.

**Comment by WesCossick** [comment]
Depending on the content of your invoice, and where it's located, you may benefit from using [`page-break-*` CSS rules](https://css-tricks.com/almanac/properties/p/page-break/).
