### ISSUE TITLE
Not center in gmail web client.

### ISSUE THREAD

**Issue by HaythemJamel** [sparksuite/simple-html-invoice-template#3]
It will be nice if it could be centered in gmail client.
![1](https://user-images.githubusercontent.com/34967941/34585794-92a360d8-f1a1-11e7-9cd8-b9c6e7e445fc.png)

**Comment by HaythemJamel** [comment]
It may this file not dedicated to be send as e-mail. It is just a proposal :) Thanks

**Comment by WesCossick** [comment]
This would have to be done outside the scope of this project, sorry.

**Comment by HaythemJamel** [comment]
Yes you have right, your code will be the be base to start new project in github for email template of invoice.

The Bests
