### ISSUE TITLE
Printable area

### ISSUE THREAD

**Issue by metehan** [sparksuite/simple-html-invoice-template#6]

**Comment by metehan** [comment]
I've edited CSS for printing but in demo page there could be an option like this -> https://printstylesheet.dbushell.com/ (Normally I wouldn't open such issue, but you called for suggestions thats why I opened) :)

**Comment by andyhill2** [comment]
Please help with printing via javascript (the table cell widths are all wrong when printed this way):-

    @media print {
        margin: 0.5cm;
        .invoice-box {
            width: 100%;
        }
    }

    <script>
       function printDiv(divName) {
       var printContents = document.getElementById(divName).innerHTML;
       var originalContents = document.body.innerHTML;
       document.body.innerHTML = printContents;
       window.print();
       document.body.innerHTML = originalContents;
       }
    </script>

...

      <input type="button" value="Print" onclick="printDiv('mydoc')"></input>

    </div>

</body>
</html>

**Comment by kufre19** [comment]
this could help

<script type="text/javascript">
    function printThis(){
        var Contents = document.getElementById("print").innerHTML;
        var newWindow = window.open("","","height=500 ,width=500");
        newWindow.document.write('<html>');
        newWindow.document.write('<body> hello');
        newWindow.document.write(Contents);
        newWindow.documentwrite('</body>');
        newWindow.document.write('</html>');
        newWindow.document.close(); 
        newWindow.print();
    }
    
    </script>

**Comment by WesCossick** [comment]
If this is still a problem, please comment; otherwise, this issue is being closed because it has grown stale. Our company's engineers will be notified of any new comments on this project going forward, though.
